---

language: python
python: "2.7"

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian9
  - distro: debian8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl

install:
  - pip install ansible

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv
  - >
  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
