---

language: python
cache: pip
python: "3.6"
env:
  - ANSIBLE_VERSION=2.4.3.0
  - ANSIBLE_VERSION=2.5.5
  - ANSIBLE_VERSION=latest
install:
  - if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip3 install -U ansible ansible-lint; else pip3 install -U ansible==${ANSIBLE_VERSION} ansible-lint; fi
script:
  - ansible-lint --version
  - ansible-lint -v .
  - ansible --version
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory -C | tee second_execution.out
  - grep 'ok.*changed.*unreachable.*failed' second_execution.out > second_execution_results.out
  - >
      if grep -vq 'changed=0.*failed=0' second_execution_results.out; then
        (echo 'Idempotence test: fail' && grep -v 'changed=0.*failed=0' site.playrecap && exit 1)
      else
        (echo 'Idempotence test: pass' && exit 0)
      fi
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
