---

language: python
python: "2.7"

env:
  - distro: centos7
  - distro: ubuntu1804
  - distro: ubuntu1604
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.2.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl

install:
  - "if [ \"$ANSIBLE_VERSION\" = \"latest\" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi",

script:
  - echo -e "[defaults]\nroles_path    = ../" > ansible.cfg
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
